### ISSUE TITLE
Error in WhileVisibleInScrollview

### ISSUE THREAD

**Issue by ckarmy** [bolav/fuse-whilevisibleinscrollview#2]
I test the **WhileVisibleInScrollview** trigger in my app Deem but don’t work fine. I have a ux (Movie.ux) that populate a StackPanel inside a ScrollView. 
- All Movie.ux trigger in the same time.
- Work inverted, the animation is active when is off the screen and when show up the trigger is desactivated.

Also its imposible to integrate with a **Each** element.

**Comment by bolav** [comment]
I was able to make this work. Can you provide a test-case?

**Comment by ckarmy** [comment]
Now work! Thanks!
